### ISSUE TITLE
"stable" version unavailable

### ISSUE THREAD

**Issue by moigagoo** [disruptek/gitnim#9]
First off, great project, thanks!

Now, to business. `git nim stable` exists with an error:
```
$ git nim stable
git-nim against https://github.com/nim-works/gitnim
+git submodule update --no-fetch frosty
fatal: reference is not a tree: 6b4a82c67d3284848f5cca6e3088d213a3c2abb4
fatal: Unable to checkout '6b4a82c67d3284848f5cca6e3088d213a3c2abb4' in submodule path 'frosty'
```

So that latest 2.0.x version I can get is 2.0.3, which apparently is a dev version.

**Comment by moigagoo** [comment]
Now, after running `git nim`, I got the command to work but it pulls an ancient 1.4.9 version:
```
$ git nim stable
git-nim against https://github.com/nim-works/gitnim

Nim Compiler Version 1.4.9 [Linux: amd64]
Compiled at 2021-10-28
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: a8aaf5a27d3c7697b22c6912bf0510f87343cb5f
active boot switches: -d:release
```

**Comment by disruptek** [comment]
I lost track of which mainline Nim was stable.  I just decided to call the version-2-0 branch stable, and updated the tag here to point to 2.0.10.  Let me know if that doesn't make sense.

You can simply
```
$ git nim
```
to pull in all the new tags, etc.
